### ISSUE TITLE
java.lang.NoSuchMethodError: Processors.PutAzureDataLake.getLogger()

### ISSUE THREAD

**Issue by slachterman** [openenergi/nifi-azure-datalake#1]
I am seeing an error when invoking the PutAzureDataLake processor, but the bulletin doesn't contain much information: _failed to invoke @OnScheduled method due to java.lang.RuntimeException: Failed while executing one of processor's OnScheduled task_

I've captured the full stack trace from nifi-app.log, see http://pastebin.com/1KdDR9cg

It appears the root cause may be tied to java.lang.NoSuchMethodError: Processors.PutAzureDataLake.getLogger()

I've validated the configuration details via the azure CLI.

**Comment by oetcoleman** [comment]
Hi Sam - are you using NiFi version 1.0 or higher by any chance?  If so then you should switch to the nifi-1.0 branch instead of the master branch.  I should probably merge this into the master branch now that NiFi 1.0 has been out for a while...

**Comment by slachterman** [comment]
Hi Toby, yes, you're absolutely right. I am using the NAR in the NiFi 1.0 branch now with NiFi 1.0 and am no longer seeing that exception. Thanks for your timely help!
